// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-public-tests.ts
import { createClient } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var list_public_tests_default = defineTool({
  name: "list_public_tests",
  title: "List public tests",
  description: "List published tests available on Milliy Sertifikat (title, subject, format, duration, price).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("tests").select("id, title, subject, format, duration_minutes, is_sunday_free").eq("is_published", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { tests: data }
    };
  }
});

// src/lib/mcp/tools/list-my-attempts.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_my_attempts_default = defineTool2({
  name: "list_my_attempts",
  title: "List my test attempts",
  description: "List the signed-in user's recent test attempts with score and status.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const uid = ctx.getUserId();
    const { data: parts } = await supabase.from("test_participants").select("id").eq("user_id", uid);
    const pids = (parts ?? []).map((p) => p.id);
    if (pids.length === 0) {
      return { content: [{ type: "text", text: "[]" }], structuredContent: { attempts: [] } };
    }
    const { data, error } = await supabase.from("test_attempts").select("id, test_id, status, score, mcq_score, written_score, total_questions, correct_answers, submitted_at, created_at").in("participant_id", pids).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { attempts: data }
    };
  }
});

// src/lib/mcp/tools/get-wallet-balance.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.102.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_wallet_balance_default = defineTool3({
  name: "get_wallet_balance",
  title: "Get wallet balance",
  description: "Return the signed-in user's wallet balance and currency.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("wallets").select("balance, currency").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const wallet = data ?? { balance: 0, currency: "UZS" };
    return {
      content: [{ type: "text", text: `Balance: ${wallet.balance} ${wallet.currency}` }],
      structuredContent: wallet
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bsjbqcewxwdthpgcxgsd";
var mcp_default = defineMcp({
  name: "milliy-sertifikat-mcp",
  title: "Milliy Sertifikat",
  version: "0.1.0",
  instructions: "Tools for Milliy Sertifikat mock-test platform. Use list_public_tests to browse published tests, list_my_attempts and get_wallet_balance to read the signed-in user's data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_public_tests_default, list_my_attempts_default, get_wallet_balance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
